# Generated by Django 5.1.5 on 2025-01-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='favicon',
        ),
    ]
