# Generated by Django 5.1.5 on 2025-01-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='contect',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
